"""initial_schema

Revision ID: 0fd7b183b5d9
Revises: 
Create Date: 2026-05-12 13:45:38.877685

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0fd7b183b5d9'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_call_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=32), nullable=False),
    sa.Column('purpose', sa.String(length=32), nullable=False),
    sa.Column('tokens_in', sa.Integer(), nullable=False),
    sa.Column('tokens_out', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_call_log_created_at'), 'ai_call_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_ai_call_log_model'), 'ai_call_log', ['model'], unique=False)
    op.create_index(op.f('ix_ai_call_log_user_id'), 'ai_call_log', ['user_id'], unique=False)
    op.create_table('drafts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('item_ids', sa.JSON(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('model', sa.String(length=32), nullable=False),
    sa.Column('variant_index', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drafts_user_id'), 'drafts', ['user_id'], unique=False)
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('subreddit', sa.String(length=64), nullable=True),
    sa.Column('author', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('num_comments', sa.Integer(), nullable=False),
    sa.Column('created_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('raw', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_items_content_hash'), 'items', ['content_hash'], unique=False)
    op.create_index(op.f('ix_items_created_utc'), 'items', ['created_utc'], unique=False)
    op.create_index(op.f('ix_items_external_id'), 'items', ['external_id'], unique=True)
    op.create_index(op.f('ix_items_source'), 'items', ['source'], unique=False)
    op.create_index(op.f('ix_items_subreddit'), 'items', ['subreddit'], unique=False)
    op.create_table('summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('one_liner', sa.String(length=200), nullable=False),
    sa.Column('bullets', sa.JSON(), nullable=False),
    sa.Column('key_quote', sa.String(length=300), nullable=True),
    sa.Column('model', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_summaries_content_hash'), 'summaries', ['content_hash'], unique=True)
    op.create_table('classifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('tag', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('reason', sa.String(length=300), nullable=False),
    sa.Column('topics', sa.JSON(), nullable=False),
    sa.Column('model', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_classifications_item_id'), 'classifications', ['item_id'], unique=True)
    op.create_index(op.f('ix_classifications_tag'), 'classifications', ['tag'], unique=False)
    op.create_table('leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('asker_username', sa.String(length=64), nullable=False),
    sa.Column('what_they_want', sa.String(length=500), nullable=False),
    sa.Column('pain_signals', sa.JSON(), nullable=False),
    sa.Column('budget_signal', sa.String(length=16), nullable=False),
    sa.Column('urgency_signal', sa.String(length=16), nullable=False),
    sa.Column('contact_hint', sa.String(length=200), nullable=True),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leads_asker_username'), 'leads', ['asker_username'], unique=False)
    op.create_index(op.f('ix_leads_item_id'), 'leads', ['item_id'], unique=True)
    op.create_index(op.f('ix_leads_score'), 'leads', ['score'], unique=False)
    op.create_table('lead_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('contacted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lead_id', 'user_id', name='uq_lead_user')
    )
    op.create_index(op.f('ix_lead_assignments_lead_id'), 'lead_assignments', ['lead_id'], unique=False)
    op.create_index(op.f('ix_lead_assignments_user_id'), 'lead_assignments', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lead_assignments_user_id'), table_name='lead_assignments')
    op.drop_index(op.f('ix_lead_assignments_lead_id'), table_name='lead_assignments')
    op.drop_table('lead_assignments')
    op.drop_index(op.f('ix_leads_score'), table_name='leads')
    op.drop_index(op.f('ix_leads_item_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_asker_username'), table_name='leads')
    op.drop_table('leads')
    op.drop_index(op.f('ix_classifications_tag'), table_name='classifications')
    op.drop_index(op.f('ix_classifications_item_id'), table_name='classifications')
    op.drop_table('classifications')
    op.drop_index(op.f('ix_summaries_content_hash'), table_name='summaries')
    op.drop_table('summaries')
    op.drop_index(op.f('ix_items_subreddit'), table_name='items')
    op.drop_index(op.f('ix_items_source'), table_name='items')
    op.drop_index(op.f('ix_items_external_id'), table_name='items')
    op.drop_index(op.f('ix_items_created_utc'), table_name='items')
    op.drop_index(op.f('ix_items_content_hash'), table_name='items')
    op.drop_table('items')
    op.drop_index(op.f('ix_drafts_user_id'), table_name='drafts')
    op.drop_table('drafts')
    op.drop_index(op.f('ix_ai_call_log_user_id'), table_name='ai_call_log')
    op.drop_index(op.f('ix_ai_call_log_model'), table_name='ai_call_log')
    op.drop_index(op.f('ix_ai_call_log_created_at'), table_name='ai_call_log')
    op.drop_table('ai_call_log')
    # ### end Alembic commands ###
