"""add_export_sync_logs

Revision ID: ebf99fbee796
Revises: 0fd7b183b5d9
Create Date: 2026-05-12 22:54:51.030700

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = 'ebf99fbee796'
down_revision: str | Sequence[str] | None = '0fd7b183b5d9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
